"use strict";
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
var __values = (this && this.__values) || function(o) {
    var s = typeof Symbol === "function" && Symbol.iterator, m = s && o[s], i = 0;
    if (m) return m.call(o);
    if (o && typeof o.length === "number") return {
        next: function () {
            if (o && i >= o.length) o = void 0;
            return { value: o && o[i++], done: !o };
        }
    };
    throw new TypeError(s ? "Object is not iterable." : "Symbol.iterator is not defined.");
};
var __read = (this && this.__read) || function (o, n) {
    var m = typeof Symbol === "function" && o[Symbol.iterator];
    if (!m) return o;
    var i = m.call(o), r, ar = [], e;
    try {
        while ((n === void 0 || n-- > 0) && !(r = i.next()).done) ar.push(r.value);
    }
    catch (error) { e = { error: error }; }
    finally {
        try {
            if (r && !r.done && (m = i["return"])) m.call(i);
        }
        finally { if (e) throw e.error; }
    }
    return ar;
};
var __spread = (this && this.__spread) || function () {
    for (var ar = [], i = 0; i < arguments.length; i++) ar = ar.concat(__read(arguments[i]));
    return ar;
};
exports.__esModule = true;
exports.CloseCall = exports.TaskResults = void 0;
var fs = require("fs");
var eventTimeWindow = 5000; // 5 seconds
var createHtml = function (issuesTable, eventsTable, shameTable) { return "\n  <html>\n    <head>\n      <style>\n        table {\n          width: 60%;\n        }\n        tr {\n          text-align: left;\n          border: 1px solid black;\n        }\n        th, td {\n          padding: 15px;\n        }\n        tr:nth-child(odd) {\n          background: #CCC\n        }\n        tr:nth-child(even) {\n          background: #FFF\n        }\n        .no-content {\n          background-color: red;\n        }\n      </style>\n    </head>\n    <body>\n        <center>\n            <font size=\"+3\"><b>Loader report: </b></font><br>\n            " + issuesTable + "\n            <font size=\"+3\"><b>Hall of shame: </b></font><br>\n            " + shameTable + "\n            <font size=\"+3\"><b>Events report: </b></font><br>\n            " + eventsTable + "\n        </center>\n        <br>\n        Generated by Squadron303 - https://github.com/matzak/squadron303\n    </body>\n  </html>\n"; };
var createIssueRow = function (item) { return "\n  <tr>\n    <td>" + item.callsign + "</td>\n    <td>" + item.cantParse + "</td>\n    <td>" + item.noBaroData + "</td>\n    <td>" + item.fixInterval + "</td>\n  </tr>\n"; };
var createIssueTable = function (rows) { return "\n  <table>\n    <tr>\n        <th>CN</td>\n        <th>Can't parse</td>\n        <th>No BARO data</td>\n        <th>Fix interval</td>\n    </tr>\n    " + rows + "\n  </table>\n"; };
var createEventRow = function (item) { return "\n  <tr>\n    <td>" + item.glider1 + "</td>\n    <td>" + item.glider2 + "</td>\n    <td>" + item.time + "</td>\n    <td>" + Math.floor(item.distance) + "</td>\n    <td>" + item.altitudeDifference + "</td>\n  </tr>\n"; };
var createEventsTable = function (rows) { return "\n  <table>\n    <tr>\n        <th>CN #1</td>\n        <th>CN #2</td>\n        <th>Time</td>\n        <th>Distance (meters)</td>\n        <th>Altitude difference (meters)</td>\n    </tr>\n    " + rows + "\n  </table>\n"; };
var createShameRow = function (item) { return "\n  <tr>\n    <td>" + item[0] + "</td>\n    <td>" + item[1] + "</td>\n    <td>" + item[2] + "</td>\n  </tr>\n"; };
var createShameTable = function (rows) { return "\n  <table>\n    <tr>\n        <th>#</td>\n        <th>CN</td>\n        <th>Number of events</td>\n    </tr>\n    " + rows + "\n  </table>\n"; };
var CloseCall = /** @class */ (function () {
    function CloseCall(glider1, glider2, time, distance, altDifference, timestamp) {
        this.glider1 = glider1;
        this.glider2 = glider2;
        this.time = time;
        this.distance = distance;
        this.altitudeDifference = altDifference;
        this.timestamp = timestamp;
    }
    return CloseCall;
}());
exports.CloseCall = CloseCall;
var TaskResults = /** @class */ (function () {
    function TaskResults() {
        this.closeCalls = [];
        this.lastEvent = undefined;
        this.shameResults = new Map();
    }
    TaskResults.prototype.reportLoadIssues = function (loadIssues) {
        this.loadIssues = loadIssues;
    };
    //TODO: refactoring needed as it may generate invalid data if used in wrong order
    TaskResults.prototype.reportEvent = function (closeCall) {
        if (this.lastEvent != undefined) {
            if (closeCall.glider1 == this.lastEvent.glider1 &&
                closeCall.glider2 == this.lastEvent.glider2 &&
                Math.abs(closeCall.timestamp - this.lastEvent.timestamp) <= eventTimeWindow) {
                // do nothing, event should be skipped
            }
            else {
                this.closeCalls.push(closeCall);
            }
        }
        else {
            this.closeCalls.push(closeCall);
        }
        this.lastEvent = closeCall;
    };
    TaskResults.prototype.loadIssuesToConsole = function () {
        console.log("Loader report:");
        console.log(this.loadIssues);
    };
    TaskResults.prototype.eventsToConsole = function () {
        this.closeCalls.forEach(function (closeCall) {
            console.log(closeCall.glider1, " vs ", closeCall.glider2, " at ", closeCall.time, "(distance: ", closeCall.distance, ", alt difference:", closeCall.altitudeDifference);
        });
        console.log("Total number of events:", this.closeCalls.length);
    };
    TaskResults.prototype.hallOfShameToConsole = function () {
        var e_1, _a;
        this.generateShameData();
        var position = 1;
        console.log("Hall of shame");
        try {
            for (var _b = __values(this.shameResults), _c = _b.next(); !_c.done; _c = _b.next()) {
                var _d = __read(_c.value, 2), key = _d[0], value = _d[1];
                console.log("#", position, " ", key + ' ' + value);
                position++;
            }
        }
        catch (e_1_1) { e_1 = { error: e_1_1 }; }
        finally {
            try {
                if (_c && !_c.done && (_a = _b["return"])) _a.call(_b);
            }
            finally { if (e_1) throw e_1.error; }
        }
    };
    TaskResults.prototype.generateHTMLReport = function () {
        var e_2, _a;
        var _b, _c;
        var issueRows = (_c = (_b = this.loadIssues) === null || _b === void 0 ? void 0 : _b.map(createIssueRow).join('')) !== null && _c !== void 0 ? _c : "";
        var issueTable = createIssueTable(issueRows);
        var eventRows = this.closeCalls.map(createEventRow).join('');
        var eventTable = createEventsTable(eventRows);
        this.generateShameData();
        var position = 1;
        var shameInput = [];
        try {
            for (var _d = __values(this.shameResults), _e = _d.next(); !_e.done; _e = _d.next()) {
                var _f = __read(_e.value, 2), key = _f[0], value = _f[1];
                shameInput.push([position, key, value]);
                position++;
            }
        }
        catch (e_2_1) { e_2 = { error: e_2_1 }; }
        finally {
            try {
                if (_e && !_e.done && (_a = _d["return"])) _a.call(_d);
            }
            finally { if (e_2) throw e_2.error; }
        }
        var shameRows = shameInput.map(createShameRow).join('');
        var shameTable = createShameTable(shameRows);
        var htmlReport = createHtml(issueTable, eventTable, shameTable);
        fs.writeFileSync("report.html", htmlReport);
        console.log("Report saved to report.html file.");
    };
    TaskResults.prototype.generateShameData = function () {
        var _this = this;
        this.shameResults = new Map();
        this.shameResults[Symbol.iterator] = function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [5 /*yield**/, __values(__spread(this.entries()).sort(function (a, b) { return b[1] - a[1]; }))];
                    case 1:
                        _a.sent();
                        return [2 /*return*/];
                }
            });
        };
        this.closeCalls.forEach(function (closeCall) {
            var _a, _b;
            var glider1Score = (_a = _this.shameResults.get(closeCall.glider1)) !== null && _a !== void 0 ? _a : 0;
            var glider2Score = (_b = _this.shameResults.get(closeCall.glider2)) !== null && _b !== void 0 ? _b : 0;
            _this.shameResults.set(closeCall.glider1, glider1Score + 1);
            _this.shameResults.set(closeCall.glider2, glider2Score + 1);
        });
    };
    return TaskResults;
}());
exports.TaskResults = TaskResults;
